[package]
name = "RedisPubSub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
redis = "0.23.3"
rocket = "=0.5.0-rc.3"
